### ISSUE TITLE
Update action.yml with Input Params annotations

### ISSUE THREAD

**Issue by robot-gamblingpro** [robot-gamblingpro/purify-issue-body-action#7]
Describe action input parameters in [action.yml](https://github.com/robot-gamblingpro/purify-issue-body-action/blob/master/action.yml).

example of usage:
```
      - uses: ./.github/actions/check-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bannedDomains: '["joxi.net", "joxi.ru"]'
          replaceTemplate: "// direct links from joxi are forbidden //"
```

where bannedDomains - json-stringified array of hostnames, replaceTemplate - replace.

Now it warns about missing annotations
![image](https://user-images.githubusercontent.com/66971204/136671897-bbf3d39f-1351-42ae-8760-05f19bf96e90.png)
